import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../Components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <Sidebar />
          <div className="w-full overflow-x-auto bg-accent">
            <div className="w-full flex justify-center mx-auto overflow-auto h-[calc(100vh)]">
              <div className="w-full mt-6"> {children}</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
